name: Build project

permissions:
  contents: write
on:
  # push:
    # branches: [ "master" ]
  # pull_request:
    # branches: [ "master" ]
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      publish_release:
        description: 'Create a release'
        required: true
        default: false

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [SPSE, SP2019, SP2016]    
    env:
      Solution_Name: ${{ github.event.repository.name }}.sln
      Project_Name: ${{ github.event.repository.name }}
      Project_Directory: ${{ github.event.repository.name }}
      Project_File_Path: ${{ github.event.repository.name }}\${{ github.event.repository.name }}.csproj
      Release_Version: ${{ vars.RELEASE_VERSION }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get current date
      id: date
      run: |
        $currentYear = (Get-Date).Year
        Add-Content -Path $env:GITHUB_OUTPUT -Value "year=$currentYear"
        
    - name: Set assembly version
      id: set-assembly-version
      uses: Yvand/assemblyinfo-update@main
      with:
        version: "${{ env.Release_Version }}"
        directory: "${{ env.Project_Name }}/Properties"
        filename: 'AssemblyInfo.cs'
        recursive: false
        copyright: "Copyright © Yvan Duhamel ${{ steps.date.outputs.year }}"

    - name: Print the assembly version generated
      shell: pwsh
      env: 
        assembly_version: ${{ steps.set-assembly-version.outputs.version }}
      run: |
        Write-Host "Assembly version: `"$($env:assembly_version)`""

    # Add MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.3.1
    
    - name: Restore Packages
      run: nuget restore "${{ env.Solution_Name }}"

    # Decode the base 64 encoded signing key
    - name: Decode the signing key
      run: |
        $data = [System.Convert]::FromBase64String("${{ secrets.BASE64_ENCODED_SIGNINGKEY }}")
        $certificatePath = Join-Path -Path $env:Project_Directory -ChildPath "${{ env.Project_Name }}.snk"
        [IO.File]::WriteAllBytes($certificatePath, $data)

    - name: Build the solution and create the wsp package
      run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration /p:IsPackaging=true /p:platform="Any CPU"
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Remove the signing key
      run: Remove-Item -path "${{ env.Project_Directory }}\\${{ env.Project_Name }}.snk"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: "${{ env.Project_Name }} ${{ env.Configuration }}"
        path: "${{ env.Project_Directory }}\\bin\\${{ env.Configuration }}\\${{ env.Project_Name }} ${{ env.Configuration }}.wsp"
      env:
        Configuration: ${{ matrix.configuration }}

  deploy:
    needs: build
    if: ${{ inputs.publish_release }} == true || startsWith(github.event.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    env:
      project-name: ${{ github.event.repository.name }}
      assembly-version: ${{ needs.build.outputs.assembly-version }}
      tag-name: ${{ needs.build.outputs.assembly-version }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          name: '${{ env.project-name }} ${{ env.tag-name }}'
          prerelease: true
          draft: true
          # tag_name: ${{ env.tag-name }}
          body: |
            ${{ env.project-name }} ${{ env.tag-name }}
          files: |
            ./${{ env.project-name }} SPSE.zip
            ./${{ env.project-name }} SP2019.zip
            ./${{ env.project-name }} SP2016.zip
